## 1. 异步

### 1.1 分块的程序

我们可以将js程序写在单个js文件中，但这个程序几乎一定是由多个块构成的。这些块只有一个是现在执行，其余的则会在将来执行，最常见的块是函数

### 1.2 事件循环

直到es6js才真正内建有直接的异步概念

js引擎并不是独立运行的，它运行在宿主环境里，对多数开发者来说就是web浏览器

> 所有这些环境都有一个共同点，那就是它们都提供了一个机制来处理程序中多个块的执行，并且执行每块时调用js引擎，这种机制被称为事件循环

换句话说，js引擎本身没有时间的概念，只是一个按需执行js任意代码片段的环境，事件（js代码执行）调度总是由包含它的环境进行

在实现上，事件循环就是一个队列，按块处理js代码中所有的事。我们可以看到，有一个用while循环实现的持续运行的循环，循环的每一轮称一个tick

一定要清楚，setTimeout并没有把你的回调函数挂在事件循环队列中，它所做的事设定一个定时器，当定时器到时之后，环境将你的回调函数放在事件循环中，这样，在未来的某个时刻的tick会摘下并且执行这个回调

如果这个时候事件循环已经满了怎么办呢，你的回调就会等待，就像正常的队列一样，它需要排在最后

```
setTimeout(() => {
	console.log("test")
}, 0)
while (1) {}
```

像这个例子，setTimeout里的任务将永远不会插入到事件循环队列中

### 1.3 并行线程

异步和并行常常被混为一谈，但其实它们两者意义完全不同

并行最常见的工具就是线程和进程，多个线程可以共享单个进程的内存

事件循环将自身的工作分为一个个任务并顺序执行，不允许对共享内存的并行访问和修改。并行和顺序执行可以共存

多线程编程是非常复杂的，因为如果不通过特殊的步骤来防止这种中断和交错运行的话，可能会得到出乎意料的，不确定的行为，通常这很让人头疼

### 1.4 竞态条件

由于js的单线程特性，函数中的代码具有原子性，即异步代码可能执行顺序不一样，但是执行顺序的最小粒度是函数块。这种函数顺序的不确定性就是通常所说的`竞态条件`

### 1.5 并发

!> 我们下面说的进程并不是计算机科学意义上的进程，它是一种逻辑上的运算序列，更多是偏理念化的。并发是概念上同时执行，但我们也要清楚因为js的时间循环，它们的单个运算实际上还是要排队执行的

两个进程同时执行就出现了并发，不管组成它们的单个运算是否并行执行，可以把并发看做进程级的并行

#### 1.5.1 非交互

对于非交互并发来说，执行顺序的不确定性并不带来任何副作用，不管顺序如何，代码总会正常工作

#### 1.5.2 交互

对于两个并发的进程之间需要交互的情况，我们需要对这些交互进行协调以避免竞态的出现

```
var res = []

function res(data) {
    if (data.url === "...") {
        ...
    }else if (data.url === "...") {
        ...
    }
}
```

#### 1.5.3 协作

还有一种并发合作方式，称为并发协作。这里的重点不再是通过共享作用域中的值进行交互，而是取得一个长期运行的进程，并将其分割成多个步骤或多批任务，是的其他并发进程有机会将自己的运算插入到时间循环队列中交替运行

```
var res = []
function res(data) {
    var chunk = data.splice(0, 1000)
    res = res.concat(chunk.map(val => val * 2))
    if(data.length > 0) {
        setTimeout(() => {res(data)}, 0)
    }
}
```

> 这里使用setTimeout(..0)来进行异步调用，它的意思就是将这个函数插入到当前事件循环队列的结尾处

:::warnin
严格来说，setTimeout(..0)并不会直接将项目插入到事件循环队.定时器会在有机会的时候插入时间。举例来说，两个连续的setTimeout(..0)调用不能保证会严格按照执行顺序处理。在nodejs中可以通过process.nextTick，但是目前没有直接的方法来适应所有环境来确保异步事件的顺序
:::

### 1.6 任务

在es6中，有一个新的概念建立在事件循环队列之上，称为任务队列。它带来的最大的影响就是Promise的异步特性。目前为止，这是一个没有公开api的机制，因此要展示清楚有些困难，所以我们目前只从概念上进行描述

任务队列最好的理解方式就是，它是挂在事件循环队列的每个tick之后的一个队列。在事件循环的每个tick之后，可能出现的异步动作不会导致一个完整的新事件添加到循环队列中，而是在当前tick的任务队列末尾添加一个项目（任务）

一个任务有可能引起更多任务被添加至同一个队列末尾

设想一个调度任务，称为schedule

```
console.log("a")
setTimeout(()=>{console.log("b")},0)
schedule(()=>{
    console.log("c")
    schedule(()=>{
        console.log("d")
    })
})
```

正确的输出顺序是"a => c => d => b"，因为任务处理是在当前事件循环tick结尾处，且定时器触发是为了调度下一个事件循环tick

任务队列和事件循环队列的区别就像是js中的微任务和宏任务的区别

* Process.nextTick
* Promise
* MutationObserver

这几种情况是进入任务队列的，也就是微任务

### 1.7 总结

js程序总是至少被分为两个块，一个是现在运行，一个是将来运行

一旦有事件需要运行，事件循环就会运行，直至队列清空，事件循环的每一轮被称为一个tick，用户交互，IO和定时器会向队列中加入事件

任何时刻一次只能从队列中处理一个事件，执行事件的时候，可能直接或者间接引发一个或者多个后续事件

并发是指两个或者多个时间随事件发展交替执行，以至于就像同时在运行

如果并发的线程之间存在交互，那么我们需要进行协调处理，或者协作利用setTimeout将大任务不断分解成小块

任务队列是es6中引入的，可以将其理解成在每个tick之后的队列

## 2. 回调

回调是最基础的异步模式

但是回调存在回调地狱的问题，它不仅仅表现在嵌套和缩进上。大量的回调函数会让我们难以看清代码的真正执行顺序

### 2.1 回调设计

#### 2.1.1 分离回调

一个用于成功通知，一个用于出错通知，这种情况下，failure往往是可选的，如果没有提供的话，就假定这个错误可以吞掉

```
function success(data) {
    ...
}
function failure(err) {
    ...
}
ajax("...", success, failure)
```

#### 2.1.2 error-first/node风格

回调的第一个参数保留用作错误对象

```
function res(err, data) {
    if(err) {...}
    else {...}
}
```

### 2.2 信任问题

回调函数的执行时间存在一个顺序问题，我们为了针对不同的回调过程中可能出现的问题，需要构造不同的工具来验证回调函数

```
function timeoutify(fn, delay) {
    var intv = setTimeout(() => {
        intv = null
        fn(new Error("Timeout"))
    }, delay)
    return function() {
        if(intv) {
            clearTimeout(intv)
            fn.apply(this, arguments)
        }
    }
}

ajax("...", timeoutify(foo, 500))
```

类似的验证函数我们还可以写很多，都是为了保护回调函数的正确执行。但是我们要知道这些都是低效的重复代码，它并不是最好的解决方案

### 2.3 总结

回调是js异步的基本单元，但是随着js越来越成熟，回调已经不够用了

第一，大脑对事情的计划是线性的，阻塞的，单线程的，但是回调表达和这个思路相悖，使得我们很难正确理解回调函数的正确执行顺序

第二，回调会受到控制反转的影响，因为回调暗中把控制权交给了第三方，这种控制转移导致一系列麻烦的信任问题，比如回调被调用的次数是否会超出预期

我们可以发明一些特定的逻辑来解决这些信任问题，但是其难度高于应有的水平，而且可能会产生更笨重和难以维护的代码

我们需要一个通用的方案来解决这些信任问题，可以复用

## 3. Promise

回调具有两个巨大的缺陷，缺乏顺序性和可信任性。Promise应运而生

### 3.1 什么是Promise

promise对象有两个特点

* 对象的状态不受外接影响。Promise对象代表一个异步操作，有三种状态，pending进行中，resolve和reject。只有异步结果的操作可以决定当前是哪一种状态，任何其他操作都无法改变这种状态
* 一旦状态改变，就不会再边，会一直保持这个结果

> 有了Promise对象，就可以将异步操作以同步操作的流程表现出来，避免了层层嵌套的回调函数，此外Promise对象提供统一的接口，使得控制异步操作更加容易

但是它也有一些缺点

* 无法取消
* 错误处理机制

#### 3.1.1 未来值

```
var x,y = 2
console.log(x + y)
```

对于上述代码，我们已经假定了x和y都已经决议好了。但是如果x和y的值只是部分决议好呢？我们来看Promise怎么解决这个问题

```
function add(xPromise, yPromise) {
    return Promise.all([xPromise, yPromise])
    .then(v => v[0] + v[1])
}
add(fetch(x), fetch(y)).then(res => console.log(res))
```

#### 3.1.2 完成事件

通常情况下，如果我们想要知道每个事件什么时候结束，我们需要手动建立监听器，如下

```
function foo(){
    ...
    return listener
}
var evt = foo()
evt.on("", ...)
evt.on("", ...)
```

使用Promise的话，我们可以这样

```
function foo(){
    return new Promise(resolve => { ... })
}
bar(fooPromise) {
    fooPromise.then(
        function() { ... },
        function() { ... }
    )
}
bar(foo())
```

### 3.2 具有then方法的鸭子类型

在promise领域，一个重要的细节是如何确定某个值会否真正的promise，或者更直接地说，它是不是一个行为方式类似于promise的值。

:::danger
promise不可以通过instanceof来判断，最主要的原因是promise有可能是从其他浏览器窗口比如iframe接收到的，这样的检查无法识别Promise实例
:::

如果我们恰好有then方法的一个对象来完成一个promise，那么它会自动被识别为thenable

### 3.3 Promise信任问题

#### 3.3.1 调用过早

一个任务有时同步完成有时异步完成，可能会导致竞态条件。Promise就不用担心这种问题，即使是立即决议的promise也总是会被异步调用

```
Promise.resolve(1).then(res => console.log(res))
console.log(0)

// 0
// 1
```

#### 3.3.2 调用过晚

一个promise决议后，这个promise上所有的通过then注册的回调都会在下一个异步时机上一次被立即调用，这些回调中的任意一个都无法影响或延误对其他回调的调用

```
p.then(()=>{
    p.then(()=>console.log("c"))
    console.log("a")
})
p.then(()=>console.log("b"))

// a
// b
// c
```

这里c就无法抢夺b的输出位置

#### 3.3.3 回调未调用

首先，没有任何东西能阻止promise向你通知它的决议（如果有决议的话）。如果promise永远不决议，我们也可以通过竞态的抽象机制来完成

```
function timeoutPr(delay) {
    return new Promise((resolve, reject) => {
        setTimeout(() => reject("timeout!"), delay)
    })
}
Promise.race([foo(), timeoutPr( 3000 )]).then(
    () => { ... },
    (err) => { ... }
)
```

#### 3.3.4 调用次数过少或者过多

Promise的特性决定它只能被决议一次，如果出于某种原因，在代码中promise决议了多次，那么它只会接受第一次决议，并默默忽略任何后续调用

#### 3.3.5 未能传递参数/环境之

promise最多只能有一个决议值(完成或者拒绝)。如果我们没有用任何值来显式决议，那么这个值就是undefined

如果使用多个参数调用resolve或者reject的话啊，第一个参数之后的参数都会被默默忽略。如果需要传多个参数，我们需要封装在单个值中传递

#### 3.3.6 吞掉错误或者异常

如果reject一个promise并且给出理由，这个值就会传给拒绝回调

如果在promise的创建过程中出现了一个异常错误，比如TypeError或者ReferenceError，那么这个异常就会被捕捉

```
var p = new Promise((resolve, reject) => {
    foo.bar() // ReferenceError
    resolve(42)
})
p.then(
    () => {...}, //永远到达不了这里
    (err) => {...}
)
```

这是一个重要的细节，Promise甚至将js异常也变成了异步行为，进而极大降低了竞态条件出现的可能

但是如果Promise在回调中出现了异常该怎么办呢，事实是这个异常需要在下一个回调中才会被捕捉到

#### 3.3.7 是可信任的Promise吗

Promise.resolve()可以快速生成一个返回值的promise

```
var p = new Promise(resolve => resolve(42))

// Equals

var p = Promise.resolve(42)
```

如果往Promise.resolve里传递一个真正的Promise，就只会返回一个promise

```
var p = Promise.resolve(42)
Promise.resolve(p) === p
```

更重要的是，如果传入一个鸭子类型的thenable数值，它就会试图展开这个值

```
var p = {
    then(cb) {cb(42)}
}
Promise.resolve(p).then(
    v => console.log(p) // 42
)
```

Promise.resolve会为所有函数的返回值都封装一层。我们可以利用Promise.resolve这个特性来包装一些疑似Promise类型的数据，让其变为真正的Promise类型

### 3.4 链式流

让Promise序列真正能够在每一部都有异步能力的关键是，Promise.resolve会直接返回接收到的真正的Promise，或展开接收到的thenable值。在决议函数中传入thenable或者Promise也会发生同样的展开

```
Promise.resolve(1).then(
    v => {
        console.log(v)
        return new Promise(resolve => resolve(42))
    }
).then(
    v => console.log(v) // 42
)
```

如果这个promise链中某个步骤出错怎么办？

```
request("url")
    .then(res => {
        foo.bar() // ReferenceError
        return ... // 永远也到不了这里
    })
    .then(
        () => { ... }, // 永远也到不了这里
        (err) => {
            console.log(err)
            return 42
        }
    )
    .then(
        msg => console.log(msg) // 42
    )
```

此外，如果Promise不传入处理函数的话，它也会有默认的resolve函数和reject函数的

```
p.then(
    function (v) {
        return v
    },
    function (err) {
        throw err
    }
)
```

### 3.5 术语

promise中resolve是决议而不是完成是有原因的，因为resolve可能是完成也有可能是拒绝

```
var rejectPr = new Promise((resolve, reject) => {
    resolve(Promise.reject("Oops"))
})
rejectPr.then(
    () => {...}, // 永远也到不了这里
    (err) => {
        console.log(err) // Oops
    }
)
```

要注意的是reject不会像resolve一样展开，所以语义上来讲reject还是很精确的

### 3.5 错误处理

try...catch结构只能用于同步处理代码，但是在promise中一个没处理好，错误可能就会被“吞掉”

```
Promise.resolve(42)
    .then(
        () => {
            console.log(msg.toLowerCase()) // TypeError
        },
        () => { ... }
    )
```

其实错误不是被吞掉了，它只是需要在下一次回调中才能获取。但是这样通过下一步才能捕捉错误的机制看起来好像无解，因为不管你最后一步是什么，总是存在着出现未捕获错误的可能性，目前还没有比较好的对应解决方案

### 3.6 Promise模式

#### 3.6.1 Promise.all([ .. ])

all里传入一个数组，里面是promise。它返回一个promise，该promise决议条件是数组里的promise均决议完成

:::tip
严格来说，数组里的内容可以使Promise，thenable，甚至是立即值，因为它每个值都会通过Promise.resolve来包装以保证等待的是一个真正的Promise
:::

注意，Promise.all的返回值是一个数组，并且这个数组里值的顺序之和数组的顺序有关，和执行顺序无关

```
function pms1() {
	return new Promise(function(resolve, reject) {
		setTimeout(function() {
			console.log("执行任务1")
			resolve("执行任务1成功")
		}, 3000)
	})
}

function pms2() {
	return new Promise(function(resolve, reject) {
		setTimeout(function() {
			console.log("执行任务2")
			resolve("执行任务2成功")
		}, 2000)
	})
}

function pms3() {
	return new Promise(function(resolve, reject) {
		setTimeout(function() {
			console.log("执行任务3")
			resolve("执行任务3成功")
		}, 2000)
	})
}
Promise.all([pms1(), pms2(), pms3()]).then(function(data) {
	console.log(data)
	console.log({}.toString.call(data))
})
// 
执行任务2
执行任务3
执行任务1
["执行任务1成功", "执行任务2成功", "执行任务3成功"]
```

#### 3.6.2 Promise.race([ .. ])

这个在Promise中称为竞态，和上者的区别就是它决议值为第一个产生决议值的promise

:::warning
一项竞赛一定要一个参赛者，所以如果你传入了一个空数组，那么它永远也不会决议而不是立即决议，要注意永远也不要传递空数组
:::


```
function pms1() {
	return new Promise(function(resolve, reject) {
		setTimeout(function() {
			console.log('执行任务1');
			resolve('执行任务1成功');
		}, 1000);
	});
}

function pms2() {
	return new Promise(function(resolve, reject) {
		setTimeout(function() {
			console.log('执行任务2');
			resolve('执行任务2成功');
		}, 2000);
	});
}

function pms3() {
	return new Promise(function(resolve, reject) {
		setTimeout(function() {
			console.log('执行任务3');
			resolve('执行任务3成功');
		}, 3000);
	});
}
Promise.race([pms1(), pms2(), pms3()]).then(function(data) {
	console.log(data);   //注意上面的延时时间
})

// 执行任务1
// 执行任务1成功
// 执行任务2
// 执行任务3
```

可以看到。race中虽然第一个跑成功了，但是其他两个也并没有停止，只是没有执行回调函数

### 3.7 PromiseAPI概述

#### 3.7.1 new Promise

#### 3.7.2 Promise.resolve, Promise.reject

#### 3.7.3 then(...) catch(...)

p.catch(fn) 等价于 p.then(null, fn)

#### 3.7.4 Promise.all Promise.race

### 3.8 Promise的局限性

#### 3.8.1 顺序错误处理

Promise的设计局限性造成了一个让人很容易中招的陷阱，即Promise链中的错误很容易被默默忽略掉.这并不是Promise独有的特性，但这是我们希望绕过的陷阱

#### 3.8.2 单一值

promise一次决议只能传递一个值，我们当然可以通过包装成一个对象的形式来解决多数据，但是这样比较麻烦。所幸es6中的解构可以帮助我们

#### 3.8.3 惯性

如果你的代码或库已经大量使用了回调，那么用Promise改造的代价可能比较大

```
if(!Promise.wrap) {
    Promise.wrap = function(fn) {
        return function() {
            var args = [].slice.call(arguments)
            return new Promise((resolve, reject) => {
                fn.apply(null, args.concat((err, v) => {
                    if(err) {reject{err}}
                    else {resolve(v)}
                }))
            })
        }
    }
}

var request = Promise.wrap(ajax)
request("url")
    .then( .. )
```

#### 3.8.4 无法取消

一旦创建一个Promise，则我们没有办法从外部停止它的进程，不过这也和它的定义相符，我们不能给出一个可以轻易被破坏的承诺promise

### 3.9 总结

promise非常好，它解决了回调的控制反转问题。它没有摒弃回调，而是将回调转交给了一个可信任的中介机制

## 4. 生成器

### 4.1 定义

正常情况下，js中，一个函数一旦执行，就会运行到结束，期间不会有任何其他代码能够打断它并且插入其中，生成器就是这样的一个异类

```
var x = 1
function* foo() {
	x++
	yield
	console.log(x)
}

var it = foo()

it.next()
it.next()
```

生成器函数当然也可以当做普通的函数来使用，不适用yield关键字也是可以的

#### 4.1.1 输入和输出

生成器函数既可以接受参数，也可以返回值

```
function* foo() {
	var a = yield 2
	console.log(a)
}

var it = foo()

var b = it.next()
console.log(b.value) // 2 (从迭代器里传出来的2)
it.next(1) // 1 (我们在外部传入1赋给a的值)
```

在`var a = yield 2`中，yield的作用是

* 将2这个直接量传出
* 抛出一个问题，这里应该插入哪个值

至此第一个yield的作用完成，函数执行停止于改行

第二次调用生成器的next则回答了第一个yield的问题，我们将1传入该值，并且依次执行后续的代码，所以会console.log出1来

:::tip
我们并没有向第一个next调用发送值，只有暂停的yield才能接受这样一个通过next传递的值，规范和所有浏览器都会默默丢弃传递给第一个next的任何东西。非要传递也可以但是会使代码产生迷惑性，所以，启动生成器时，一定要用不带参数的next
:::

#### 4.1.2 多个迭代器

同一个生成器的多个实例可以同时运行，不相互影响，但是它们也可以做到交互

```
var a = 1
var b = 2
function* foo() {
	a++
	yield
	b = b * a
	a = (yield b) + 3
}
function* bar() {
	b--
	yield
	a = (yield 8) * b
	b = a * (yield 2)
}
// step的作用是将yield爬出来的值再原封不动传回去
function step(gen) {
	var it = gen()
	var last
	return function() {
		last = it.next(last).value
	}
}
var s1 = step(foo)
var s2 = step(bar)

s2() // a=1, b=1
s2() // yield 8
s1() // a=2, b=1
s2() // a=8*b=8

s1() // b=b*a=8,yield b(8)

s1() // a=b+3=11
s2() // b=a*2=22
```

### 4.2 生成器产生值

#### 4.2.1 生产者和迭代器

假定你要产生一系列值，其中每个值都和前面一个有特定的关系，要实现这一点，需要一个有状态的生产者能够记住其生成的最后一个值

我们当然可以实现一个闭包的版本，这是最简单能够想到的

我们在这里，可以实现设计模式里的迭代器模式

```
var something = function() {
	var nextVal
	return {
		[Symbol.iterator]: function() {
			return this
		},
		next: function() {
			if (nextVal === undefined) {
				nextVal = 1
			} else {
				nextVal = 3 * nextVal + 6
			}
			return { done: false, value: nextVal }
		}
	}
}

something.next().value // 1
something.next().value // 9
something.next().value // 33
something.next().value // 105
```

之所以要给迭代器一个Symbol.iterator接口是因为让其能够被for..of..遍历

```
for(var v of something) {
    console.log(v)
    if(v > 500) break
}
```

除了构建自己的迭代器，许多js的内建数据结构，有自己默认的迭代器。array有，但是一般的对象没有，我们可以用Object.keys/for..in..

#### 4.2.2 迭代器生成器

生成器 = 调用后返回一个迭代器，如上例中something就是一个迭代器，因为它本身就有iterable接口和next方法   

> 停止生成器，可以通过break或者return

```
var it = something()
for(var v of something) {
    console.log(v)
    if(v > 500) {
        it.return('hello world')
    }
}
```

### 4.3 异步迭代生成器

生成器和异步编码模式到底有什么关系

```
function foo() {
    ajax({
        ...
        it.next(data) // 成功的回调
    })
}
function* main() {
    var text = yield foo()
    console.log(text)
}
var it = main()
it.next()
```

通过yield可以帮我们以同步的代码组织结构来处理异步的代码，比如下面的代码就不能正常运转

```
var text = ajax(...)
console.log(text)
```

#### 4.3.1 同步错误处理

我们已经看到yield是如何让赋值语句暂停等待异步事件完成，精彩的部分在于yield也可以让生成器能够捕获错误，

```
foo(){
	ajax({
		url: "...",
		function (data) {
			it.next(data)
		},
		function () {
			it.throw("error")
		}
	})
}
try {
	var text = yield foo()
	console.log(text)
} catch (e) {
	console.log(err)
} finally {
	
}
```

### 4.4 yield+promise

普通的异步迭代器缺失了promise的可信任性和可组合性。最好的办法就是yield一个promise，然后通过这个promise来控制生成器的迭代器

```
function foo() {
	return Promise.resolve(1)
}
function* main() {
	try {
		var text = yield foo()
		console.log(text)
	} catch (err) {
		console.error(err)
	}
}
var it = main()
var p = it.next().value
p.then(
	text => it.next(text),
	err => it.throw(err)
)
```

#### 4.4.1 async await

最好的解决方案还是这个，不过我们这里重点介绍yield，就先略过

#### 4.4.2 生成器中的promise并发

想象这样一个场景，你需要从两个不同的来源获取数据，然后把响应组合在一起以形成第三个请求

```
function* foo(params) {
	var p1 = request(url1)
	var p2 = request(url2)
	var r1 = yield p1
	var r2 = yield p2
	var r3 = yield reques(url3 + r1 + r2)
}
```

我们通过这样一个类似于手动实现Promise.all的方式，来做到p1，p2两个异步请求并发进行，无论哪一个先决议，都会因为yield而保持状态

> 作为一个风格提醒，要注意你的生成器内部包含多少promise逻辑，我们要尽量将异步的细节隐藏起来,如下例，一个非常有效的做法是，把你的promise逻辑隐藏在一个只从生成器代码中调用的函数内部（比如下面的bar函数）

```
function bar() {
	return Promise.all(p1, p2)
}
function *bar() {
	var results = yield bar()
	...
}
```

### 4.5 生成器委托

我们如果想要在一个生成器里调用另外一个生成器，一个比较好的做法是生成器委托

```
function *foo() {
	console.log("*foo start")
	yield 3
	yield 4
	console.log("*foo end")
}
function *bar() {
	yield 1
	yield 2
	yield *foo()
	yield 5
}

var it = bar()
it.next() // 1
it.next() // 2
it.next() // *foo start 3
it.next() // 4
it.next() // *foo end 5
```

#### 4.5.1 消息委托

生成器委托也可以用于双向消息传递


```
function* foo() {
	console.log("inside foo", yield "B")
	console.log("inside foo", yield "C")
	return "D"
}
function* bar() {
	console.log("inside bar", yield "A")
	console.log("inside bar", yield* foo())
	console.log("inside bar", yield "E")
	return "F"
}
var it = bar()
console.log("outside", it.next().value)
console.log("outside", it.next(1).value)
console.log("outside", it.next(2).value)
console.log("outside", it.next(3).value)
console.log("outside", it.next(4).value)

// output

outside A
inside bar 1
outside B
inside foo 2
outside C
inside foo 3
inside bar D
outside E
inside bar 4
outside F
```

#### 4.5.2 递归委托

yield委托可以跟踪任意多委托步骤，甚至可以委托自己

```
function *foo(val) {
    if(val > 1){
        val = yield *foo(val - 1)   
    }
    return yield request(url + val)
}
```

### 4.6 总结

生成器是es6的一个新的函数类型，它不像普通函数那样总是运行到结束，而是它可以在运行当中暂停

这种交替的暂停和回复是合作性的而不是抢占性，这意味着生成器具有独一无二的能力来暂停自身

生成器不仅是一种控制机制，也是一种双向消息传递机制

在异步控制流程方面，生成器的关键优点在于，生成器内部的代码是以自然的同步顺序表达任务的一系列步骤，其技巧在于，我们把可能的异步操作隐藏在了yield后面

## Refer

* [彻底吃透Js执行机制](https://mp.weixin.qq.com/s?__biz=MzIxNjgwMDIzMA==&mid=2247484265&idx=1&sn=85712d5ab8da6fd04de15958cf322306&scene=21#wechat_redirect)